CREATE DATABASE quartz;
CREATE TABLE TIMERJOB(
  id VARCHAR(36) NOT NULL PRIMARY KEY,
  job_name VARCHAR(20) NOT NULL ,
  job_group VARCHAR(20) NOT NULL ,
  cron_expression VARCHAR(20) NOT NULL ,
  job_desc VARCHAR(100) NOT NULL ,
  job_status VARCHAR(10) NOT NULL,
  class_name VARCHAR(100) NOT NULL,
  method_name VARCHAR(20) NOT NULL
);